config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root "welcome#index"
  devise_for :users

  namespace :api do
    namespace :v1 do
      get 'chats/:id/messages', to: 'messages#index', as: 'chat_messages'
      post 'chats/:id/messages/create', to: 'messages#create', as: 'create_chat_message'
      put 'messages/:id', to: 'messages#update', as: 'update_chat_message'
    end
  end


  resources :chat_list_items
  resources :blocklists
  resources :favourites
  resources :message_statuses
  resources :messages
  resources :chats
  resources :profiles
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :profile
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  load_and_authorize_resource
  before_action :set_favourite, only: %i[ show edit update destroy ]

  # GET /favourites or /favourites.json
  def index
    @favourites = Favourite.all

    render json: @favourites
  end

  # GET /favourites/1 or /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites or /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)

    respond_to do |format|
      if @favourite.save
        format.html { redirect_to @favourite, notice: "Favourite was successfully created." }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1 or /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to @favourite, notice: "Favourite was successfully updated." }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1 or /favourites/1.json
  def destroy
    @favourite.destroy
    respond_to do |format|
      format.html { redirect_to favourites_url, notice: "Favourite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favourite_params
      params.require(:favourite).permit(:id)
    end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_form.html.erb
<%= form_with(model: favourite) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
        <% favourite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourites</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <td><%= favourite.id %></td>
        <td><%= link_to 'Show', favourite %></td>
        <td><%= link_to 'Edit', edit_favourite_path(favourite) %></td>
        <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favourite', new_favourite_path %>

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @favourite.id %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>