config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root "welcome#index"
  devise_for :users

  namespace :api do
    namespace :v1 do
      get 'chats/:id/messages', to: 'messages#index', as: 'chat_messages'
      post 'chats/:id/messages/create', to: 'messages#create', as: 'create_chat_message'
      put 'messages/:id', to: 'messages#update', as: 'update_chat_message'
    end
  end


  resources :chat_list_items
  resources :blocklists
  resources :favourites
  resources :message_statuses
  resources :messages
  resources :chats
  resources :profiles
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    # user ||= User.new # guest user (not logged in)


    if user && user.admin?
      can :manage, :all
      cannot :update, User
    elsif user
      can :index, Welcome
      can :read, Chat, Chat.all do |chat|
        chat.users.include?(user) ? true : false
      end
      can :read, Profile
      can [:update, :destroy], Profile, user: user
    else
      can :index, Welcome
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blocklist.rb
class Blocklist < ApplicationRecord
  belongs_to :blocker_user,  class_name: "User"
  belongs_to :blocked_user,  class_name: "User"
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :chat_list_items
  has_many :users, :through => :chat_list_items

  has_many :messages
end

app/models/chat_list_item.rb
class ChatListItem < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :profile
end

app/models/message.rb
class Message < ApplicationRecord
  has_one :message_status
  belongs_to :user
  belongs_to :chat
end

app/models/message_status.rb
class MessageStatus < ApplicationRecord
  belongs_to :message
  has_one :user, :through => :message
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :favourites
  # has_many :saved_by_users, :through => :favourites, class_name: "User", foreign_key: :user_id
  has_many :saved_by_users, :through => :favourites, class_name: "User", source: :user, foreign_key: :user_id
  has_one_attached :avatar
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one :profile

  has_many :chat_list_items
  has_many :chats, :through => :chat_list_items

  has_many :favourites
  # has_many :saved_profiles, :through => :favourites, class_name: "Profile", foreign_key: :profile_id
  has_many :saved_profiles, :through => :favourites, class_name: "Profile", source: :profile, foreign_key: :profile_id


  has_many :messages

  has_many :blocker_users
  has_many :blocked_users
end

app/models/welcome.rb
class Welcome 
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  load_and_authorize_resource
  before_action :set_chat, only: %i[ show edit update destroy ]

  # GET /chats or /chats.json
  def index
    @chats = current_user.chats
  end

  # GET /chats/1 or /chats/1.json
  def show
    chat_members = @chat.users.ids
    chat_members.delete(current_user.id)
    @other_user_name = User.where(id: chat_members).first.profile.name
    @messages = @chat.messages
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: "Chat was successfully created." }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:id, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  load_and_authorize_resource
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocklists_helper.rb
module BlocklistsHelper
end

app/helpers/chat_list_items_helper.rb
module ChatListItemsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/_chat.html.erb
<% chat_members = chat.users.ids %>
<% chat_members.delete(current_user.id) %>
<% other_user = User.where(id: chat_members).first.profile %>
<%= render partial: "application/avatar", :locals => {:profile => other_user} %>
<h2><%= link_to other_user.name, chat %></h2>


<%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %>
<br><br><br><br>

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<%= render @chats %>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <strong>Chat with <%= @other_user_name %></strong>
</p>

<div class="messages">
  <%= render @messages %>
</div>

<%= link_to 'Back', chats_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<body>
<%= link_to "Feed", profiles_path %>
<%= link_to "Chats", chats_path %>
</body>