config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root "welcome#index"
  devise_for :users

  namespace :api do
    namespace :v1 do
      get 'chats/:id/messages', to: 'messages#index', as: 'chat_messages'
      post 'chats/:id/messages/create', to: 'messages#create', as: 'create_chat_message'
      put 'messages/:id', to: 'messages#update', as: 'update_chat_message'
    end
  end


  resources :chat_list_items
  resources :blocklists
  resources :favourites
  resources :message_statuses
  resources :messages
  resources :chats
  resources :profiles
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blocklist.rb
class Blocklist < ApplicationRecord
  belongs_to :blocker_user,  class_name: "User"
  belongs_to :blocked_user,  class_name: "User"
end

app/controllers/blocklists_controller.rb
class BlocklistsController < ApplicationController
  load_and_authorize_resource
  before_action :set_blocklist, only: %i[ show edit update destroy ]

  # GET /blocklists or /blocklists.json
  def index
    @blocklists = Blocklist.all
  end

  # GET /blocklists/1 or /blocklists/1.json
  def show
  end

  # GET /blocklists/new
  def new
    @blocklist = Blocklist.new
  end

  # GET /blocklists/1/edit
  def edit
  end

  # POST /blocklists or /blocklists.json
  def create
    @blocklist = Blocklist.new(blocklist_params)

    respond_to do |format|
      if @blocklist.save
        format.html { redirect_to @blocklist, notice: "Blocklist was successfully created." }
        format.json { render :show, status: :created, location: @blocklist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blocklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocklists/1 or /blocklists/1.json
  def update
    respond_to do |format|
      if @blocklist.update(blocklist_params)
        format.html { redirect_to @blocklist, notice: "Blocklist was successfully updated." }
        format.json { render :show, status: :ok, location: @blocklist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blocklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocklists/1 or /blocklists/1.json
  def destroy
    @blocklist.destroy
    respond_to do |format|
      format.html { redirect_to blocklists_url, notice: "Blocklist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blocklist
      @blocklist = Blocklist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blocklist_params
      params.require(:blocklist).permit(:id, :type)
    end
end

app/helpers/blocklists_helper.rb
module BlocklistsHelper
end

app/views/blocklists/_form.html.erb
<%= form_with(model: blocklist) do |form| %>
  <% if blocklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blocklist.errors.count, "error") %> prohibited this blocklist from being saved:</h2>

      <ul>
        <% blocklist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blocklists/edit.html.erb
<h1>Editing Blocklist</h1>

<%= render 'form', blocklist: @blocklist %>

<%= link_to 'Show', @blocklist %> |
<%= link_to 'Back', blocklists_path %>

app/views/blocklists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blocklists</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocklists.each do |blocklist| %>
      <tr>
        <td><%= blocklist.id %></td>
        <td><%= blocklist.type %></td>
        <td><%= link_to 'Show', blocklist %></td>
        <td><%= link_to 'Edit', edit_blocklist_path(blocklist) %></td>
        <td><%= link_to 'Destroy', blocklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blocklist', new_blocklist_path %>

app/views/blocklists/new.html.erb
<h1>New Blocklist</h1>

<%= render 'form', blocklist: @blocklist %>

<%= link_to 'Back', blocklists_path %>

app/views/blocklists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @blocklist.id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @blocklist.type %>
</p>

<%= link_to 'Edit', edit_blocklist_path(@blocklist) %> |
<%= link_to 'Back', blocklists_path %>